# -*- coding: utf-8 -*-
"""Traffic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UxYG3-54Rl-7OrW9kLqGTopiKWXkwjTz
"""

import pandas as pd
df = pd.read_csv('traffic.csv')
df.head(10)

from google.colab import drive
drive.mount('/content/drive')

inputs = df.drop('Junction', axis='columns')

target = df['Junction']

from sklearn.preprocessing import LabelEncoder
le_DateTime = LabelEncoder()
le_Junction = LabelEncoder()
le_Vehicles = LabelEncoder()
le_ID = LabelEncoder()

inputs['DateTime_n'] = le_DateTime.fit_transform(inputs['DateTime'])
inputs['Vehicles_n'] = le_Vehicles.fit_transform(inputs['Vehicles'])
inputs['ID_n'] = le_ID.fit_transform(inputs['ID'])

inputs

inputs_n = inputs.drop(['DateTime','Vehicles','ID'], axis='columns')

inputs_n

target

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs_n, target, test_size=0.2, random_state=4)

x_test

from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(x_train, y_train)

model.score(x_train, y_train)

inputs.to_csv("number.csv")

y_pred = model.predict(x_test)

from sklearn import metrics
print("Accuracy: ", metrics.accuracy_score(y_test, y_pred))